overviews/as_riverside.bmp
overviews/as_riverside.txt
gfx/env/riverzcape1bk.tga
gfx/env/riverzcape1dn.tga
gfx/env/riverzcape1ft.tga
gfx/env/riverzcape1lf.tga
gfx/env/riverzcape1rt.tga
gfx/env/riverzcape1up.tga
as_riverside.wad